apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: todo-web-application
  name: todo-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-web-application
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: todo-web-application
    spec:
      containers:
      - image: zikozee/todo-web-application-mysql:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: todo-web-application
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
