#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true


# use environment variable RDS_HOSTNAME, if not found use localhost::::: use RDS_PORT if not found use 3306
#spring.datasource.url=jdbc:mysql://localhost:3306/todos
#spring.datasource.username=todos-user
#spring.datasource.password=dummytodos


spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:todos}
    username: ${RDS_USERNAME:todos-user}
    password: ${RDS_PASSWORD:dummytodos}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        web: INFO



management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'